
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: install
  image: ruby:2.3.7
  commands:
  - bundle -v
  - bundle install --jobs=3 --retry=3
  - rake

- name: test
  image: ruby:2.3.7
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - rake
