
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: install
  image: ruby:2.3.7
  commands:
  - gem install bundler --default -v "2.1.4"
  - gem list bunder
  - bundle -v
  - bundle _2.1.4_ install --jobs=1 --retry=1
  - rake

- name: test
  image: ruby:2.3.7
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - rake
