version: '3'
services:
  mysql:
    image: mysql:5.7.17
    command: --sql-mode=""
    restart: always
    volumes:
      - ./mysql_data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: educoder

  redis:
    image: redis:3.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  web:
    image: guange/educoder:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - redis